name: Daily Leaderboard Post

on:
  schedule:
    # Her gün 07:00 UTC = 10:00 Turkey time (weekdays)
    - cron: '0 7 * * 1-5'
  workflow_dispatch: # Manuel tetikleme için

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: scripts

      - name: Run daily leaderboard poster
        run: node post-leaderboard.mjs
        working-directory: scripts
        env:
          TWITTER_API_KEY:        ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET:     ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN:   ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET:  ${{ secrets.TWITTER_ACCESS_SECRET }}
          INSTAGRAM_USER_ID:      ${{ secrets.INSTAGRAM_USER_ID }}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          IMGBB_API_KEY:          ${{ secrets.IMGBB_API_KEY }}
